name: opus_flutter_example
description: Demonstrates how to use the opus_flutter plugin.
version: 2.0.0+2
publish_to: "none"

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  opus_dart: ^3.0.1
  flutter:
    sdk: flutter
  share_plus: ^7.2.1
  opus_flutter:
    path: ../
  cupertino_icons: ^1.0.6
  platform_info: ^4.0.2
dependency_overrides:
  opus_flutter_android:
    path: ../../opus_flutter_android
  opus_flutter_ios:
    path: ../../opus_flutter_ios
  opus_flutter_platform_interface:
    path: ../../opus_flutter_platform_interface
  opus_flutter_web:
    path: ../../opus_flutter_web
  opus_flutter_windows:
    path: ../../opus_flutter_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/s16le_16000hz_mono.raw
    - assets/download.js
