name: opus_flutter
description: Loads a DynamicLibrary of opus for usage with opus_dart on flutter platforms.
repository: https://github.com/EPNW/opus_flutter/tree/master/opus_flutter
version: 3.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # TODO: Revisit this (either update this part in the design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  opus_flutter_platform_interface: ^3.0.0
  opus_flutter_android: ^3.0.0
  opus_flutter_ios: ^3.0.0
  opus_flutter_windows: ^3.0.0
  opus_flutter_web: ^3.0.3

flutter:
  plugin:
    platforms:
      android:
        default_package: opus_flutter_android
      ios:
        default_package: opus_flutter_ios
      windows:
        default_package: opus_flutter_windows
      web:
        default_package: opus_flutter_web